-- Tabla round_buy de Supabase (la llena vlr_pipeline/upload.py desde tables/table_round_buy.csv).
-- Una fila por ronda; joinea con round_info por team_map_round_id.
-- Generado desde vlr_pipeline.tables.round_buy_columns(): si cambian las columnas, regenerar.
-- Correr una vez en el SQL editor de Supabase ANTES de la proxima corrida del pipeline que
-- tenga filas de round_buy (si la tabla no existe, el upsert falla y la serie no se marca en match_id).
create table if not exists public.round_buy (
  "team_map_round_id" text primary key,
  "series_id" text,
  "map_id" text,
  "round" integer,
  "team_a" text,
  "team_b" text,
  "side_team_a" text,
  "reg_id" text,
  "tour_id" text,
  "player_1_team_a" text,
  "player_1_team_a_agent" text,
  "player_1_team_a_weapon" text,
  "player_1_team_a_shield" text,
  "player_1_team_a_spend" integer,
  "player_1_team_a_bank" integer,
  "player_2_team_a" text,
  "player_2_team_a_agent" text,
  "player_2_team_a_weapon" text,
  "player_2_team_a_shield" text,
  "player_2_team_a_spend" integer,
  "player_2_team_a_bank" integer,
  "player_3_team_a" text,
  "player_3_team_a_agent" text,
  "player_3_team_a_weapon" text,
  "player_3_team_a_shield" text,
  "player_3_team_a_spend" integer,
  "player_3_team_a_bank" integer,
  "player_4_team_a" text,
  "player_4_team_a_agent" text,
  "player_4_team_a_weapon" text,
  "player_4_team_a_shield" text,
  "player_4_team_a_spend" integer,
  "player_4_team_a_bank" integer,
  "player_5_team_a" text,
  "player_5_team_a_agent" text,
  "player_5_team_a_weapon" text,
  "player_5_team_a_shield" text,
  "player_5_team_a_spend" integer,
  "player_5_team_a_bank" integer,
  "player_1_team_b" text,
  "player_1_team_b_agent" text,
  "player_1_team_b_weapon" text,
  "player_1_team_b_shield" text,
  "player_1_team_b_spend" integer,
  "player_1_team_b_bank" integer,
  "player_2_team_b" text,
  "player_2_team_b_agent" text,
  "player_2_team_b_weapon" text,
  "player_2_team_b_shield" text,
  "player_2_team_b_spend" integer,
  "player_2_team_b_bank" integer,
  "player_3_team_b" text,
  "player_3_team_b_agent" text,
  "player_3_team_b_weapon" text,
  "player_3_team_b_shield" text,
  "player_3_team_b_spend" integer,
  "player_3_team_b_bank" integer,
  "player_4_team_b" text,
  "player_4_team_b_agent" text,
  "player_4_team_b_weapon" text,
  "player_4_team_b_shield" text,
  "player_4_team_b_spend" integer,
  "player_4_team_b_bank" integer,
  "player_5_team_b" text,
  "player_5_team_b_agent" text,
  "player_5_team_b_weapon" text,
  "player_5_team_b_shield" text,
  "player_5_team_b_spend" integer,
  "player_5_team_b_bank" integer
);

create index if not exists round_buy_series_id_idx on public.round_buy (series_id);
